version: 2
jobs:
  maven-jobs: 
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run:
          name: test
          command: mvn test
      - run:
          name: package
          command: mvn package
      - run: ls
      - run: cp Dockerfile /tmp/my-project/target/
      - run: ls target
      - persist_to_workspace:
          root: /tmp/my-project/target
          paths: 
            - app.jar
            - Dockerfile
  
  docker-jobs:
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - attach_workspace:
          at: target
      - run: pwd
      - run: ls target
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build -t gustavoghioldi/democi:latest /tmp/my-project/target/.
      - run: docker push gustavoghioldi/democi:latest
  
  deploy-jobs:
    machine:
      java:
        version: oraclejdk8
    steps:
      - checkout
      - run: aws lambda invoke 
            --invocation-type RequestResponse 
            --function-name swarm-ci-deploy 
            --region us-east-1 
            --payload "{\"name\":\"democi\"}" output.txt
      - run: cat output.txt


workflows:
  version: 2
  mvn-dock:
    jobs:
      - maven-jobs
      - docker-jobs:
          requires:
            - maven-jobs
      - deploy-jobs:
          requires:
            - docker-jobs



      