version: 2
jobs:
  maven-jobs: 
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run:
          name: test
          command: mvn test
      - run:
          name: package
          command: mvn package
      - run: ls
      - run: cp Dockerfile /tmp/my-project/target/
      - run: cp cluster_deploy.json /tmp/my-project/target/
      - run: ls target
      - persist_to_workspace:
          root: /tmp/my-project/target
          paths: 
            - app.jar
            - Dockerfile
            - cluster_deploy.json
  
  docker-jobs:
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - attach_workspace:
          at: target
      - run: pwd
      - run: ls target
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build -t gustavoghioldi/democi:latest /tmp/my-project/target/.
      - run: docker push gustavoghioldi/democi:latest
  
  deploy-job:
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - attach_workspace:
          at: target
    steps:
      - run: |
          function readJson {  \
            UNAMESTR=`uname` \
            if [[ "$UNAMESTR" == 'Linux' ]]; then \
            SED_EXTENDED='-r' \
            elif [[ "$UNAMESTR" == 'Darwin' ]]; then \
            SED_EXTENDED='-E' \
            fi; \
            VALUE=`grep -m 1 "\"${2}\"" ${1} | sed ${SED_EXTENDED} 's/^ *//;s/.*: *"//;s/",?//'` \
            if [ ! "$VALUE" ]; then \
            echo "Error: Cannot find \"${2}\" in ${1}" >&2; \
            exit 1; \
            else \
            echo $VALUE ; \
            fi; }
      - run: NAME=`readJson target/cluster_deploy.json name` || exit 1;  
      - run: echo $NAME

workflows:
  version: 2
  mvn-dock:
    jobs:
      - maven-jobs
      - docker-jobs:
          requires:
            - maven-jobs
      - deploy-jobs
          requires:
            - docker-jobs



      