version: 2
jobs:
  maven-jobs: 
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run:
          name: test
          command: mvn test
      - run:
          name: package
          command: mvn package
      - run: ls target
      - persist_to_workspace:
          root: /tmp/my-project/target
          path: app.jar
  
  docker-jobs:
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - attach_workspace:
          at: workspace
      - run: pwd
      - run: ls
      - run: docker info

workflows:
  version: 2
  mvn-dock:
    jobs:
      - maven-jobs
      - docker-jobs:
          requires:
            - maven-jobs



      