version: 2
jobs:
  #maven-jobs:
  build: 
    machine:
      java:
        version: oraclejdk8
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run:
          name: test
          command: mvn test
      - run: pwd
      - run:
          name: package
          command: mvn package
      - run: ls 
      